swapi:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres_container
      user: user
      password: assword
      port: 5432
      dbname: swapipostgres
      schema: public
      threads: 1
      connect_timeout: 10
    dev-fal:
      type: fal
      db_profile: dev